### ISSUE TITLE
Not openeing on Ubuntu 17.10

### ISSUE THREAD

**Issue by barfittc** [Witik/RiderUserSecrets#1]
I can not open the user secrets with this plugin on Ubuntu 17.10. I can confirm the directory and secrets.json file exist, and have content. Is this plugin suppose to open a new editor window?

**Comment by Witik** [comment]
Yes, it's supposed to open a new editor window, I'll look into it

**Comment by CarlosLanderas** [comment]
Not working for me on Ubuntu 18.04, not opening as well. The problem is the file is not being created correctly:

if you go to ~microsoft/usercrets you can find a file created like this:

'usersecretsprojectfileid/secrets.json'.

It seems it's nor handling correctly directory and file paths.

**Comment by Witik** [comment]
I submitted a new version, hopefully this will fix the problem.

**Comment by Witik** [comment]
Just tested this on elementary OS 0.4.1, and works like a charm.
The plugin update is still awaiting approval from JetBrains, please report back when you get the chance to try it again.

**Comment by CarlosLanderas** [comment]
Thanks @Witik, the plugin is still in on the approval process, as soon as it is published ill test it with Ubuntu 18.04.

**Comment by CarlosLanderas** [comment]
Hello @Witik  it is still not working for me. The window is opening now and secrets are editable but the path is wrong:

instead of creating the user secrets folder within the path:

<pre>/home/clanderas/.microsoft</pre>

it is appending an extra ~ symbol creating the files in this path:


<pre>/home/clanderas/~/.microsoft</pre>

Due to that the secrets are not read by the applications:

**Comment by Witik** [comment]
I've submitted a new version which should remedy this issue.

**Comment by CarlosLanderas** [comment]
Thanks for the support @Witik, I will check it asap

**Comment by Witik** [comment]
@CarlosLanderas have you had the chance to test the new version?

**Comment by CarlosLanderas** [comment]
@Witik it seems to be working in Ubuntu now!. Thanks ;)
