### ISSUE TITLE
The plugin is incompatible with Rider 2020.3

### ISSUE THREAD

**Issue by SeanFeldman** [Witik/RiderUserSecrets#11]
![image](https://user-images.githubusercontent.com/1309622/102109456-4c36bb00-3df1-11eb-8d91-7108445b1615.png)

**Comment by SeanFeldman** [comment]
@maartenba any idea why would this be the case? Are some of the APIs used by the plugin deprecated? Thank you.

**Comment by maartenba** [comment]
The plugin is limited to one major version afaik, so will need a new release.

**Comment by SeanFeldman** [comment]
cc @Witik

**Comment by maartenba** [comment]
(on a PR)

**Comment by Witik** [comment]
@maartenba Thanks for the PR!

@SeanFeldman The new version is published to JetBrains and will be approved in the coming days. If you cannot wait for that release, you may also download the [latest release](https://github.com/Witik/RiderUserSecrets/releases/tag/1.0.1) manually.

Additionally, I removed the `until-build` version from the plugin, so if the API doesn't break, it should keep working the next major Rider release 😄

**Comment by maartenba** [comment]
Awesome!

**Comment by SeanFeldman** [comment]
Thank you, @maartenba and @Witik!

**Comment by maartenba** [comment]
It's up \o/ Thanks everyone!
