### ISSUE TITLE
Rider 2021.1.2 broke secrets plugin again

### ISSUE THREAD

**Issue by SeanFeldman** [Witik/RiderUserSecrets#17]
@maartenba perhaps it's time for Rider to officially provide support for user secrets?

**Comment by maartenba** [comment]
On the "official support", I will let @AlexanderGillissen decide. Happy to start a conversation around including the plugin (or similar functionality) into Rider core. (It seems we have [an issue for this](https://youtrack.jetbrains.com/issue/RIDER-11406) already).

/cc @fornever @mfilippov

In the meanwhile, happy to make PR for the issue, if I could reproduce the issue you are seeing.
Just tested with a number of projects in 2021.1.2, and all seems fine. Can you be more specific about what you are seeing/leads you to say "it broke"?

**Comment by SeanFeldman** [comment]
> Just tested with a number of projects in 2021.1.2, and all seems fine. Can you be more specific about what you are seeing/leads you to say "it broke"?

I wasn't able to see the option in the solution menu anymore. Ironically, this was resolved when rebooting. Don't ask 🤦‍♂️ 
Categorize as a PEBCAK issue.

Regarding the official support, perhaps that could be taken outside of this issue. Assuming, @AlexanderGillissen wants that.

**Comment by Witik** [comment]
Regarding "official support", I'm all for it. The reason for developing this plugin was that this functionality was something I found Rider lacked when I initially switched from VS.

**Comment by SeanFeldman** [comment]
@Witik, you're awesome.
@maartenba, you are as well. You'll get extra points if could kick off the next step - getting Rider to adopt this functionality. 

PS: by absorbing the plugin, does that mean JetBrains becomes a young MSFT? 😝

**Comment by maartenba** [comment]
Big +1 on being awesome, @Witik !

The development team is aware, and there's [this issue](https://youtrack.jetbrains.com/issue/RIDER-11406). No promises on timeline though :-)

In the mean time, will try and make sure to provide PRs when needed.

**Comment by maartenba** [comment]
FYI this will become part of Rider 2022.3 🥳
