### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by a-a-k** [Witik/RiderUserSecrets#2]
Could you provide how to use this plugin? I'm new in Rider IDE. In VS2017 I can click RMB on the solution node in the solution explorer and choose "Manage user secrets". How it works here?

**Comment by jens-jonsson** [comment]
Doesn't apply to solution level, only on project level:

RMB on Project -> Tools ->"Open project user secrets"

**Comment by a-a-k** [comment]
I have to ask one more thing - is that feature works only for already exists secrets? I do not able to create new one and at the same time **Open project user secrets** is disabled. No way.

**Comment by Witik** [comment]
Yes, you need the UserSecretsId property in your project file. The plugin creates a new UserSecrets json file if it doesn’t exist.

I’ll probably update the plugin in the near future that it can add user secrets to a new project.

**Comment by Witik** [comment]
Added usage information in the readme
