### ISSUE TITLE
No support for MsBuild variables

### ISSUE THREAD

**Issue by SeanFeldman** [Witik/RiderUserSecrets#8]
## Expected behaviour 

Process and evaluate `UserSecretsId` node to respect MsBuild properties.

It's possible to use MsBuild's well-defined variables as user secret values.
For example, using Visual Studio 2019, for a project `MyProject.csproj`

```xml
<UserSecretsId>$(MSBuildProjectName)</UserSecretsId>
```

`secrets.json` file will be created in `MyProject` folder rather than a guild.

## Actual behaviour

MsBuild value is treated as text and is used as-is, creating `secrets.json` in a folder named `$(MSBuildProjectName)`.

https://github.com/Witik/RiderUserSecrets/blob/27b11e601ab866cc45c733c5081374327c958888/src/eu/gillissen/rider/usersecrets/OpenUserSecretsAction.kt#L64-L68

**Comment by maartenba** [comment]
FYI, the `com.jetbrains.rider.run.environment.MSBuildEvaluator` class may help in figuring out the `$(MSBuildProjectName)` (or full evaluated property value of `UserSecretsId`)

**Comment by SeanFeldman** [comment]
Thank you so much, @maartenba!

@Witik, are you planning to release it soon? This would solve my [pain point with Rider and secrets](https://weblogs.asp.net/sfeldman/user-secrets-the-human-readable-version).

**Comment by Witik** [comment]
I just released the new version and submitted it to Jetbrains for approval.
If you want to use it beforehand, you can download the [artifact from the release](https://github.com/Witik/RiderUserSecrets/releases/tag/1.0.0)

**Comment by maartenba** [comment]
Thanks @Witik !

**Comment by SeanFeldman** [comment]
Thank you, both 🙇 

@maartenba, do you know how lengthy that approval process is?

**Comment by Witik** [comment]
@SeanFeldman I got an email this afternoon with the approval, so the update should be available
